version: "3.7"
services:
  ## streamer
  service:
    volumes:
      # bind-mount for sss authentication
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    environment:
      # provides configuration files from docker secrets
      - STREAMER_SERVICE_CONFIG=/run/secrets/streamer-service-config.json
      - STREAMER_MAILER_CONFIG=/run/secrets/streamer-mailer-config.json
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer
    secrets:
      - streamer-service-config.json
      - streamer-mailer-config.json
  ui:
    environment:
      # provides configuration files from docker secrets
      - STREAMER_UI_CONFIG=/run/secrets/streamer-ui-config.json
      - STREAMER_SERVICE_CONFIG=/run/secrets/streamer-service-config.json
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer-ui
    secrets:
      - streamer-service-config.json
      - streamer-ui-config.json
      - streamer-ui-adconfig.json
      - streamer-ui-ldapscert.crt
    ports:
      - ${STREAMER_UI_EXTERNAL_PORT:-9000}:9000
    volumes:
      - ${PROJECT_CEPHFS_VOL}:/project_cephfs
      - ${PROJECT_VOL}:/project
      - ${STREAMER_UI_LOG_VOL}:/opt/streamer-ui-server/log
  ui-db:
    ports:
      - ${STREAMER_UI_DB_EXTERNAL_PORT:-9001}:${STREAMER_UI_DB_PORT:-5432}
    volumes:
      - ${STREAMER_UI_DB_DATA_VOL}:/var/lib/postgresql/data

  ## stager
  stager-db:
    volumes:
      - ${STAGER_DB_DATA_VOL}:/data

  # stager api server
  stager-api-server:
    volumes:
      - ${STAGER_API_CONFIG}:/etc/stager/api-server.yml:ro
      - ${PROJECT_VOL:-/project}:/project
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # stager worker
  stager-worker:
    volumes:
      - ${STAGER_IRODS_ICAT_CERT}:/opt/irods/ssl/icat.pem:ro
      - ${STAGER_WORKER_CONFIG}:/etc/stager/worker.yml:ro
      - ${PROJECT_VOL:-/project}:/project
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

networks:
  default:
    attachable: true
  proxynet:
    external: true

secrets:
  streamer-service-config.json:
    external: true
  streamer-mailer-config.json:
    external: true
  streamer-ui-config.json:
    external: true
  streamer-ui-adconfig.json:
    external: true
  streamer-ui-ldapscert.crt:
    external: true