version: "3.7"
services:
  ## streamer
  service:
    volumes:
      # bind-mount for sss authentication
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
      - ${STREAMER_SERVICE_CONFIG}:/opt/streamer/config/default.json
      - ${STREAMER_MAILER_CONFIG}:/opt/streamer/config/mailer.json
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer
  ui:
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer-ui
    ports:
      - ${STREAMER_UI_EXTERNAL_PORT:-9000}:9000
    volumes:
      - ${PROJECT_CEPHFS_VOL}:/project_cephfs
      - ${PROJECT_VOL}:/project
      - ${STREAMER_UI_LOG_VOL}:/opt/streamer-ui-server/log
      - ${STREAMER_SERVICE_CONFIG}:/opt/streamer-ui-server/config/streamer-service-config.json
      - ${STREAMER_UI_CONFIG}:/opt/streamer-ui-server/config/streamer-ui-config.json
  ui-db:
    volumes:
      - ${STREAMER_UI_DB_DATA_VOL}:/var/lib/postgresql/data

  ## stager
  stager-db:
    volumes:
      - ${STAGER_DB_DATA_VOL}:/data

  # stager api server
  stager-api-server:
    volumes:
      - ${STAGER_API_CONFIG}:/etc/stager/api-server.yml:ro
      - ${PROJECT_VOL:-/project}:/project
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # stager worker
  stager-worker:
    volumes:
      - ${STAGER_IRODS_ICAT_CERT}:/opt/irods/ssl/icat.pem:ro
      - ${STAGER_WORKER_CONFIG}:/etc/stager/worker.yml:ro
      - ${PROJECT_VOL:-/project}:/project
      - ${PROJECT_CEPHFS_VOL:-/project_cephfs}:/project_cephfs
    deploy:
      placement:
        constraints:
          - node.labels.IpRange==44
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

networks:
  default:
    attachable: true
  proxynet:
    external: true