version: '3.7'
services:
  ui:
    build:
      context: ./streamer-ui
    image: ${DOCKER_REGISTRY:-dccn}/streamer-ui
    environment:
      - STREAMER_UI_HOST=${STREAMER_UI_HOST:-0.0.0.0}
      - STREAMER_UI_PORT=${STREAMER_UI_PORT:-9000}
      - STREAMER_UI_BUFFER_DIR=${STREAMER_UI_BUFFER_DIR}
      - STREAMER_URL_PREFIX=http://service:${STREAMER_SERVICE_PORT:-3001}
    volumes:
      - ${PROJECT_VOL}:/project
    networks:
      - ui_net
    depends_on:
      - ui-db
  ui-db:
    image: postgres:12
    environment:
      - POSTGRES_HOST=${STREAMER_UI_HOST:-0.0.0.0}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./streamer-ui//ui-db/init/01-initialize-database.sh:/docker-entrypoint-initdb.d/01-initialize-database.sh:ro
      - ./streamer-ui/ui-db/pgdata:/var/lib/postgresql/data
    networks:
      - ui_net
    restart: always

volumes:
  postgres:

networks:
  ui_net:
