version: "3.7"

services:
  service:
    volumes:
      # bind-mount for sss authentication
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    environment:
      # provides configuration files from docker secrets
      - STREAMER_SERVICE_CONFIG=/run/secrets/streamer-service-config.json
      - STREAMER_MAILER_CONFIG=/run/secrets/streamer-mailer-config.json
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer
    secrets:
      - streamer-service-config.json
      - streamer-mailer-config.json
  ui:
    environment:
      # provides configuration files from docker secrets
      - STREAMER_UI_CONFIG=/run/secrets/streamer-ui-config.json
      - STREAMER_UI_ADCONFIG=/run/secrets/streamer-ui-adconfig.json
      - STREAMER_UI_LDAPSCERT=/run/secrets/streamer-ui-ldapscert.crt
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer-ui

networks:
  default:
    attachable: true
  proxynet:
    external: true

secrets:
  streamer-service-config.json:
    external: true
  streamer-mailer-config.json:
    external: true
  streamer-ui-config.json:
    external: true
  streamer-ui-adconfig.json:
    external: true
  streamer-ui-ldapscert.crt:
    external: true
