version: '3.7'
services:
  db:
    build:
      context: ./redis
    image: ${DOCKER_REGISTRY:-dccn}/redis
    user: root
    volumes:
      - ${STREAMER_DB_DATA_VOL}:/data
  service:
    build:
      context: ./streamer
    image: ${DOCKER_REGISTRY:-dccn}/streamer:${DOCKER_IMAGE_TAG:-latest}
    user: root
    environment:
      - REDIS_HOST=db
      - REDIS_PORT=6379
      - STREAMER_SERVICE_PORT=${STREAMER_SERVICE_PORT:-3001}
    volumes:
      - ${STREAMER_SERVICE_LOG_VOL}:/opt/streamer/log
      - ${STREAMER_SERVICE_CRON_VOL}:/cron
      - ${HOME_VOL}:/home:ro
      - ${PROJECT_VOL}:/project
    depends_on:
      - db
  ui:
    build:
      context: ./streamer-ui
    image: ${DOCKER_REGISTRY:-dccn}/streamer-ui:${DOCKER_IMAGE_TAG:-latest}
    environment:
      STREAMER_UI_HOST:
      STREAMER_UI_PORT:
      STREAMER_UI_PROJECT_DIR:
      STREAMER_UI_CRON_DIR:
      STREAMER_UI_BUFFER_DIR:
      STREAMER_URL_PREFIX:
      STREAMER_UI_DB_HOST:
      STREAMER_UI_DB_PORT:
      STREAMER_UI_DB_USER:
      STREAMER_UI_DB_PASSWORD:
      STREAMER_UI_DB_NAME:
      STREAMER_UI_MOCK_AUTH:
      STREAMER_UI_MOCK_PROJECT_DATABASE:
      STREAMER_UI_INTERNAL_SERVER_API_UR:
      STREAMER_UI_EXTERNAL_SERVER_API_URL:
    depends_on:
      - service
      - ui-db
  ui-db:
    image: postgres:12
    environment:
      POSTGRES_HOST:
      POSTGRES_PORT:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DATABASE:
      GRAFANA_USER:
      GRAFANA_PASSWORD:
    ports:
      - ${STREAMER_UI_DB_EXTERNAL_PORT:-9001}:${STREAMER_UI_DB_PORT:-5432}
    volumes:
      - ${STREAMER_UI_DB_INIT_VOL}/01-initialize-database.sh:/docker-entrypoint-initdb.d/01-initialize-database.sh:ro
    restart: always
