version: "3.7"
services:
  service:
    volumes:
      # bind-mount for sss authentication
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    environment:
      # provides configuration files from docker secrets
      - STREAMER_SERVICE_CONFIG=/run/secrets/streamer-service-config.json
      - STREAMER_MAILER_CONFIG=/run/secrets/streamer-mailer-config.json
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer
    secrets:
      - streamer-service-config.json
      - streamer-mailer-config.json
  ui:
    environment:
      # provides configuration files from docker secrets
      - STREAMER_UI_CONFIG=/run/secrets/streamer-ui-config.json
      - STREAMER_UI_ADCONFIG=/run/secrets/streamer-ui-adconfig.json
      - STREAMER_UI_LDAPSCERT=/run/secrets/streamer-ui-ldapscert.crt
      - STREAMER_SERVICE_CONFIG=/run/secrets/streamer-service-config.json
    networks:
      default:
      # join the proxynet with hostname alias
      proxynet:
        aliases:
          - streamer-ui
    secrets:
      - streamer-service-config.json
      - streamer-ui-config.json
      - streamer-ui-adconfig.json
      - streamer-ui-ldapscert.crt
    ports:
      - ${STREAMER_UI_EXTERNAL_PORT:-9000}:${STREAMER_UI_PORT:-9000}
    volumes:
      - ${PROJECT_CEPHFS_VOL}:/project_cephfs
      - ${PROJECT_VOL}:${STREAMER_UI_PROJECT_DIR}
      - ${STREAMER_UI_CRON_VOL}:${STREAMER_UI_CRON_DIR}
      - ${STREAMER_UI_LOG_VOL}:${STREAMER_UI_LOG_DIR}
  ui-db:
    ports:
      - ${STREAMER_UI_DB_EXTERNAL_PORT:-9001}:${STREAMER_UI_DB_PORT:-5432}
    volumes:
      - ${STREAMER_UI_DB_DATA_VOL}:/var/lib/postgresql/data

networks:
  default:
    name: streamer4user-net
    attachable: true
  proxynet:
    external: true

secrets:
  streamer-service-config.json:
    external: true
  streamer-mailer-config.json:
    external: true
  streamer-ui-config.json:
    external: true
  streamer-ui-adconfig.json:
    external: true
  streamer-ui-ldapscert.crt:
    external: true
