version: "3.7"
services:
  ui:
    environment:
      - STREAMER_UI_CONFIG=${STREAMER_UI_CONFIG:-/opt/streamer-ui-server/config/streamer-ui-config.json.template}
      - STREAMER_UI_ADCONFIG=${STREAMER_UI_ADCONFIG:-/opt/streamer-ui-server/config/streamer-ui-adconfig.json.template}
      - STREAMER_UI_LDAPSCERT=${STREAMER_UI_LDAPSCERT:-/opt/streamer-ui-server/config/streamer-ui-ldapscert.crt.template}
      - STREAMER_UI_DB_HOST=ui-db
      - STREAMER_UI_DB_PORT=${STREAMER_UI_DB_PORT:-5432}
      - STREAMER_UI_DB_USER=${STREAMER_UI_DB_USER:-postgres}
      - STREAMER_UI_DB_PASSWORD=${STREAMER_UI_DB_PASSWORD:-postgres}
      - STREAMER_UI_DB_NAME=${STREAMER_UI_DB_NAME:-postgres}
    ports:
      - ${STREAMER_UI_PORT:-9000}:${STREAMER_UI_PORT:-9000}
    depends_on:
      - ui-db
  ui-db:
    image: postgres:12
    environment:
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PORT=${STREAMER_UI_DB_PORT:-5432}
      - POSTGRES_USER=${STREAMER_UI_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${STREAMER_UI_DB_PASSWORD:-postgres}
      - POSTGRES_DATABASE=${STREAMER_UI_DB_NAME:-postgres}
      - PGDATA=/data/postgres
      - GRAFANA_USER=${STREAMER_UI_GRAFANA_USER:-grafanareader}
      - GRAFANA_PASSWORD=${STREAMER_UI_GRAFANA_PASSWORD:-password}
    ports:
      - ${STREAMER_UI_DB_EXTERNAL_PORT:-9001}:${STREAMER_UI_DB_PORT:-5432}
    volumes:
      - ${STREAMER_UI_DB_INIT_VOL}/01-initialize-database.sh:/docker-entrypoint-initdb.d/01-initialize-database.sh:ro
      - ${STREAMER_UI_DB_DATA_VOL}:/var/lib/postgresql/data
    restart: always