version: "3.7"

services:
  service:
    # bind-mount for sss authentication
    volumes:
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    networks:
      default:
      proxynet:
        aliases:
          - streamer
    secrets:
      - service_config.json
      - mailer_config.json
  ui:
    networks:
      default:
      proxynet:
        aliases:
          - streamer-ui

networks:
  proxynet:
    external: true

secrets:
  service_config.json:
    external: true
  mailer_config.json:
    external: true