version: '3.7'
services:
  ui:
    build:
      context: ./streamer-ui
    image: ${DOCKER_REGISTRY:-dccn}/streamer-ui:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - ${STREAMER_UI_EXTERNAL_PORT:-9000}:9000
    volumes:
      - ${STREAMER_SECRETS_DIR}:/opt/streamer-ui-server/config
      - ${STREAMER_UI_PROJECT_DIR}
      - ${STREAMER_UI_CRON_DIR}
      - ${STREAMER_UI_LOG_DIR}
  ui-db:
    ports:
      - ${STREAMER_UI_DB_PORT:-5432}:${STREAMER_UI_DB_PORT:-5432}
    volumes:
      - /var/lib/postgresql/data
