version: '3.7'
services:
  ui:
    build:
      context: ./streamer-ui
      args:
        REACT_APP_STREAMER_UI_MOCK_AUTH: ${STREAMER_UI_MOCK_AUTH}
        REACT_APP_STREAMER_UI_MOCK_PROJECT_DATABASE: ${STREAMER_UI_MOCK_PROJECT_DATABASE}
        REACT_APP_STREAMER_UI_INTERNAL_SERVER_API_URL: ${STREAMER_UI_INTERNAL_SERVER_API_URL}
        REACT_APP_STREAMER_UI_EXTERNAL_SERVER_API_URL: ${STREAMER_UI_EXTERNAL_SERVER_API_URL}
    image: ${DOCKER_REGISTRY:-dccn}/streamer-ui:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - ${STREAMER_UI_PORT:-3900}:${STREAMER_UI_PORT:-3900}
    volumes:
      - ${STREAMER_UI_PROJECT_DIR}
      - ${STREAMER_UI_CRON_DIR}
  ui-db:
    ports:
      - ${STREAMER_UI_DB_PORT:-5432}:${STREAMER_UI_DB_PORT:-5432}
    volumes:
      - /var/lib/postgresql/data
