version: "2"
services:
  ui:
    build:
      context: ./streamer-ui
    image: streamer-ui
    networks:
      - nw_streamer
    ports:
      - 9000:9000
    environment:
      - STREAMER_UI_HOST=0.0.0.0
      - STREAMER_UI_PORT=9000
      - STREAMER_UI_BUFFER_DIR=${STREAMER_UI_BUFFER_DIR}
      - STREAMER_URL_PREFIX=http://service:3001
    volumes:
      - ${PROJECT_VOL}:/project

networks:
  nw_streamer:
    driver: bridge
